In [1]:
import torch
import torch.nn as nn
import numpy as np

In [80]:
#Construct the network

myNet = nn.Sequential(
    nn.Linear(2, 10),
    nn.Sigmoid(),
    nn.Linear(10, 10),
    nn.Sigmoid(),
    nn.Linear(10, 1),
)
print(myNet)

Sequential(
  (0): Linear(in_features=2, out_features=10, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=10, out_features=10, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=10, out_features=1, bias=True)
)


In [81]:
#input

x = torch.randn(2)
x.requires_grad_(True)
y = (x[0]**2 + x[1]**2) / 2

In [82]:
y_pred=myNet(x)
loss = (y_pred-y)**2

In [83]:
loss.backward()

In [98]:
for par in myNet.parameters():
    print(par.grad)

tensor([[ 1.3901e-01,  3.9938e-01],
        [ 7.1599e-02,  2.0570e-01],
        [ 6.3773e-02,  1.8322e-01],
        [-2.0976e-01, -6.0263e-01],
        [ 5.8109e-02,  1.6694e-01],
        [ 3.8310e-03,  1.1006e-02],
        [-7.2732e-02, -2.0896e-01],
        [-4.1857e-02, -1.2025e-01],
        [ 3.2518e-04,  9.3424e-04],
        [ 6.4334e-02,  1.8483e-01]])
tensor([ 1.5214,  0.7836,  0.6979, -2.2957,  0.6360,  0.0419, -0.7960, -0.4581,
         0.0036,  0.7041])
tensor([[ 0.0166,  0.0148,  0.0414,  0.0077,  0.0441,  0.0143,  0.0335,  0.0253,
          0.0424,  0.0285],
        [-0.5519, -0.4933, -1.3753, -0.2544, -1.4673, -0.4751, -1.1127, -0.8416,
         -1.4105, -0.9464],
        [ 0.5305,  0.4742,  1.3221,  0.2445,  1.4106,  0.4567,  1.0697,  0.8091,
          1.3559,  0.9098],
        [-0.4676, -0.4180, -1.1652, -0.2155, -1.2432, -0.4025, -0.9428, -0.7131,
         -1.1951, -0.8019],
        [ 1.2470,  1.1147,  3.1076,  0.5747,  3.3155,  1.0735,  2.5143,  1.9017,
          3.187

In [86]:
#Get the list for w and b

tmp=[]
for parameter in myNet.parameters():
    tmp.append(parameter)

In [87]:
w_list[2]=w_list[2].reshape((1,10))

In [88]:
w_list[2].shape

(1, 10)

In [89]:
tmp[0]=w1
tmp[1]=b1
tmp[2]=w2
tmp[3]=b2
tmp[4]=w3
tmp[5]=b3

In [105]:
w_list = [w1, w2, w3]
b_list = [b1, b2, b3]

In [116]:
#Define the sigmoid function
def sigmoid_derive(x):
    return sigmoid(x) * (1-sigmoid(x))
def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))

In [100]:
# get the list for partial derivative
p_b = [np.zeros(b.shape) for b in b_list]
p_w = [np.zeros(w.shape) for w in w_list]

In [107]:
# perform forward propogation
z1 = np.dot(w_list[0], x) + b_list[0]
z1_act = sigmoid(z1)
z2 = np.dot(w_list[1], z1_act) + b_list[1]
z2_act = sigmoid(z2)
z3 = np.dot(w_list[2], z2_act) + b_list[2]
z3

array([-4.109867], dtype=float32)

In [110]:
#Compute gradient for layers

# For last layer
loss2 = (z3 - y)**2
delta = 2 * (z3 - y)
p_b[-1] = delta
p_w[-1] = np.dot(delta, z2_act.transpose().reshape((1,10)))
# For second layer
delta = np.dot(w_list[-2+1].transpose(), delta) * sigmoid_derive(z2)
p_b[-2] = delta
p_w[-2] = np.dot(delta.reshape((10,1)), z1_act.transpose().reshape((1, 10)))
# For first layer
delta = np.dot(w_list[-3+1].transpose(), delta) * sigmoid_prime(z1)
p_b[-3] = delta
p_w[-3] = np.dot(delta.reshape((10, 1)), x.transpose().reshape((1, 2)))

In [112]:
p_b

[array([ 1.521391  ,  0.7836008 ,  0.69794935, -2.295661  ,  0.6359585 ,
         0.04192757, -0.7959975 , -0.4580964 ,  0.00355894,  0.70409155],
       dtype=float32),
 array([ 0.05093963, -1.6933409 ,  1.6278435 , -1.4347221 ,  3.8262208 ,
         0.6656767 ,  0.36848304,  0.37829703,  1.9715214 ,  0.4041521 ],
       dtype=float32),
 array([-8.296993], dtype=float32)]

In [113]:
p_w

[array([[ 1.3901260e-01,  3.9937705e-01],
        [ 7.1599208e-02,  2.0570135e-01],
        [ 6.3773058e-02,  1.8321717e-01],
        [-2.0975924e-01, -6.0262895e-01],
        [ 5.8108825e-02,  1.6694409e-01],
        [ 3.8310080e-03,  1.1006316e-02],
        [-7.2731920e-02, -2.0895557e-01],
        [-4.1857205e-02, -1.2025389e-01],
        [ 3.2518720e-04,  9.3424838e-04],
        [ 6.4334281e-02,  1.8482955e-01]], dtype=float32),
 array([[ 0.01660184,  0.01483984,  0.04137196,  0.00765151,  0.04413997,
          0.01429247,  0.03347309,  0.02531752,  0.04243053,  0.0284714 ],
        [-0.5518803 , -0.4933077 , -1.3752913 , -0.25435224, -1.4673057 ,
         -0.4751119 , -1.1127162 , -0.8416077 , -1.4104804 , -0.9464494 ],
        [ 0.5305339 ,  0.47422686,  1.3220959 ,  0.24451405,  1.4105512 ,
          0.45673487,  1.069677  ,  0.80905485,  1.3559239 ,  0.9098413 ],
        [-0.4675933 , -0.4179663 , -1.1652472 , -0.21550578, -1.2432085 ,
         -0.4025495 , -0.9427745 , -0.7130